### ISSUE TITLE
Scala REPL in 2.12.8 is not compatible with the compat lib

### ISSUE THREAD

**Issue by skonto** [scala/scala-collection-compat#202]
```
./bin/scala -cp scala-collection-compat_sjs1.0.0-M7_2.13.0-RC1-1.0.0.jar 
Welcome to Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_191).
Type in expressions for evaluation. Or try :help.
scala>   import scala.collection.compat._
java.io.IOException: Scala signature package has wrong version
 expected: 5.0
 found: 5.2 in package.class
	at scala.reflect.internal.pickling.UnPickler$Scan.checkVersion(UnPickler.scala:124)
	at scala.reflect.internal.pickling.UnPickler$Scan.<init>(UnPickler.scala:66)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:47)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:894)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$20(ClassfileParser.scala:1119)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:1119)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:525)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:162)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:133)
```

**Comment by skonto** [comment]
I used the wrong jar version feel free to close it.
