### ISSUE TITLE
Linking error on Scala.js

### ISSUE THREAD

**Issue by gabro** [scala/scala-collection-compat#243]
While using `Factory` on Scala.js I get this error:

```
[error] Referring to non-existent method scala.collection.compat.package$.FactoryOps(scala.collection.generic.CanBuildFrom)scala.collection.compat.PackageShared$FactoryOps
```

<details>
<summary>Full stack trace</summary>

```
[error] Referring to non-existent class scala.collection.compat.package$
[error]   called from metaconfig.internal.FactoryDecoder$$anon$1.read(metaconfig.Conf)metaconfig.Configured
[error]   called from metaconfig.internal.ConfGet$.getOrElse(metaconfig.Conf,java.lang.Object,java.lang.String,scala.collection.Seq,metaconfig.ConfDecoder)metaconfig.Configured
[error]   called from metaconfig.Conf.getSettingOrElse(metaconfig.generic.Setting,java.lang.Object,metaconfig.ConfDecoder)metaconfig.Configured
[error]   called from metaconfig.AllTheAnnotations$$anon$1.read(metaconfig.Conf)metaconfig.Configured
[error]   called from metaconfig.DeriveConfCodecSuite.$$anonfun$check$1(metaconfig.ConfCodec,java.lang.Object)org.scalatest.compatible.Assertion
[error]   called from metaconfig.DeriveConfCodecSuite.check(java.lang.String,java.lang.Object,metaconfig.ConfCodec)scala.Unit
[error]   called from metaconfig.DeriveConfCodecSuite.<init>()
[error]   called from metaconfig.DeriveConfCodecSuite.<clinit>()
[error]   called from core module analyzer
[error] involving instantiated classes:
[error]   metaconfig.internal.FactoryDecoder$$anon$1
[error]   metaconfig.internal.ConfGet$
[error]   metaconfig.ConfOps$$anon$6
[error]   metaconfig.ConfOps$$anon$2
[error]   metaconfig.ConfOps$$anon$5
[error]   metaconfig.ConfOps$$anon$1
[error]   metaconfig.ConfOps$$anon$4
[error]   metaconfig.ConfOps$$anon$3
[error]   metaconfig.Conf$Bool
[error]   metaconfig.Conf$Num
[error]   metaconfig.Conf$Lst
[error]   metaconfig.Conf$Obj
[error]   metaconfig.Conf$Str
[error]   metaconfig.Conf$Null
[error]   metaconfig.AllTheAnnotations$$anon$1
[error]   metaconfig.DeriveConfCodecSuite
[error] Referring to non-existent method scala.collection.compat.package$.FactoryOps(scala.collection.generic.CanBuildFrom)scala.collection.compat.PackageShared$FactoryOps
[error]   called from metaconfig.internal.FactoryDecoder$$anon$1.read(metaconfig.Conf)metaconfig.Configured
[error]   called from metaconfig.internal.ConfGet$.getOrElse(metaconfig.Conf,java.lang.Object,java.lang.String,scala.collection.Seq,metaconfig.ConfDecoder)metaconfig.Configured
[error]   called from metaconfig.Conf.getSettingOrElse(metaconfig.generic.Setting,java.lang.Object,metaconfig.ConfDecoder)metaconfig.Configured
[error]   called from metaconfig.AllTheAnnotations$$anon$1.read(metaconfig.Conf)metaconfig.Configured
[error]   called from metaconfig.DeriveConfCodecSuite.$$anonfun$check$1(metaconfig.ConfCodec,java.lang.Object)org.scalatest.compatible.Assertion
[error]   called from metaconfig.DeriveConfCodecSuite.check(java.lang.String,java.lang.Object,metaconfig.ConfCodec)scala.Unit
[error]   called from metaconfig.DeriveConfCodecSuite.<init>()
[error]   called from metaconfig.DeriveConfCodecSuite.<clinit>()
[error]   called from core module analyzer
[error] involving instantiated classes:
[error]   metaconfig.internal.FactoryDecoder$$anon$1
[error]   metaconfig.internal.ConfGet$
[error]   metaconfig.ConfOps$$anon$6
[error]   metaconfig.ConfOps$$anon$2
[error]   metaconfig.ConfOps$$anon$5
[error]   metaconfig.ConfOps$$anon$1
[error]   metaconfig.ConfOps$$anon$4
[error]   metaconfig.ConfOps$$anon$3
[error]   metaconfig.Conf$Bool
[error]   metaconfig.Conf$Num
[error]   metaconfig.Conf$Lst
[error]   metaconfig.Conf$Obj
[error]   metaconfig.Conf$Str
[error]   metaconfig.Conf$Null
[error]   metaconfig.AllTheAnnotations$$anon$1
[error]   metaconfig.DeriveConfCodecSuite
[error] org.scalajs.core.tools.linker.LinkingException: There were linking errors
[error]         at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:163)
[error]         at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:111)
[error]         at org.scalajs.core.tools.linker.frontend.LinkerFrontend.$anonfun$link$3(LinkerFrontend.scala:66)
[error]         at org.scalajs.core.tools.logging.Logger.time(Logger.scala:31)
[error]         at org.scalajs.core.tools.logging.Logger.time$(Logger.scala:29)
[error]         at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error]         at org.scalajs.core.tools.linker.frontend.LinkerFrontend.link(LinkerFrontend.scala:65)
[error]         at org.scalajs.core.tools.linker.Linker.$anonfun$link$1(Linker.scala:55)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at org.scalajs.core.tools.linker.Linker.guard(Linker.scala:72)
[error]         at org.scalajs.core.tools.linker.Linker.link(Linker.scala:53)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1(ClearableLinker.scala:55)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1$adapted(ClearableLinker.scala:55)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.linkerOp(ClearableLinker.scala:66)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.link(ClearableLinker.scala:55)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$11(ScalaJSPluginInternal.scala:327)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$10(ScalaJSPluginInternal.scala:332)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (coreJS / Test / fastOptJS) org.scalajs.core.tools.linker.LinkingException: There were linking errors
[error] Total time: 24 s, completed Aug 6, 2019 8:19:26 AM
```

</details>

The issue can be reproduced by cloning this PR https://github.com/olafurpg/metaconfig/pull/72 and running `++ 2.12.8 coreJS/test` in sbt. In general, the combinations of running the `core` tests (which involve using `Factory`) look like this:

|        | JVM | JS | Native |
|--------|:---:|:--:|:------:| 
|2.11.12 | ✅ |  🛑 |  ✅    |
|2.12.8  | ✅ |  🛑 |  ✅    |
|2.13.0  | ✅ |  ✅ |  ✅    |

**Comment by gabro** [comment]
Update: in case it helps the investigation, I've removed scala-collection-compat in favor of a small adapter (basically the same s-c-c does for Factory, just with only the stuff I needed) and it seems to work fine.

https://github.com/olafurpg/metaconfig/pull/72/commits/367bc95b167d596f8384cc5236dd79a8cea510f7#diff-83fdc55af8b62cc646beb5fae774932c

**Comment by gabro** [comment]
Nvm, I forgot to use `%%%` 🤕 Thanks @sjrd for spotting the error
